# Use a slim version of Python for a smaller image size
FROM python:3.11.4-slim

# Install environment dependencies
RUN apt-get update \
    && apt-get install -y netcat-openbsd --no-install-recommends \
    && apt-get clean

# Set environment variables to prevent Python from writing pyc files to disc (equivalent to python -B option)
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set working directory
WORKDIR /usr/src/app

# Install Python dependencies
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Add entrypoint script and make it executable
COPY ./entrypoint.sh /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

# Copy the rest of the application
COPY . /usr/src/app

# Run server via the entrypoint script
CMD ["./entrypoint.sh"]
