# Use NGINX to serve the static files
FROM nginx:1.15.8-alpine

# Remove the default NGINX configuration
RUN rm /etc/nginx/conf.d/default.conf

# Copy the site-specific configuration file
COPY prod.conf /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/nginx.conf

COPY .  /usr/share/nginx/html

# Copy the build output to the NGINX html directory
# COPY /build /usr/share/nginx/html

# Expose port 80 to the outside world
EXPOSE 80

# Start NGINX
CMD ["nginx", "-g", "daemon off;"]
