name: Backend Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: custom-postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: backend_test
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build custom PostgreSQL image
        run: |
          docker build -t custom-postgres:latest -f services/postgres/Dockerfile .

      - name: Build backend image
        run: |
          docker build -t backend-dev:latest -f services/backend/Dockerfile-dev .

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r services/backend/requirements.txt

      - name: Wait for Postgres
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for postgres container..."
            sleep 20
          done

      - name: Set up Docker Compose
        run: |
          docker-compose -f docker-compose-dev.yml up --build -d
          sleep 20

      - name: Run tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/backend_dev
          DATABASE_TEST_URL: postgres://postgres:postgres@localhost:5432/backend_test
          APP_SETTINGS: project.config.TestingConfig
          PYTHONPATH: services/backend
        run: |
          cd services/backend
          export APP_SETTINGS=project.config.TestingConfig
          export PYTHONPATH=$(pwd)
          export DATABASE_TEST_URL=postgresql://postgres:postgres@localhost:5432/backend_test
          export DATABASE_URL=postgresql://postgres:postgres@localhost:5432/backend_dev
          pytest
